---
- name: Get users with /bin/bash shell
  shell: "getent passwd | grep '/bin/bash' | cut -d: -f1 | tail -n+2"
  register: bash_users
  changed_when: false

#- name: Change passwords for users
#  user:
#    name: "{{ item }}"
#    update_password: always
#    password: "{{ 'new_password' | password_hash('sha512') }}"
#  with_items: "{{ bash_users.stdout_lines }}"
- name: Force to change password for users
  command: chage -d 0 {{ item }}
  with_items: "{{ bash_users.stdout_lines }}"
